check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,7 +43,17 @@ jobs:
       # Компиляция C++ библиотеки для Windows
       - name: Build C++ library (Windows)
         if: matrix.os == 'windows-latest'
-        run: g++ -shared -o D:\a\ITMO_programming_tools_lab4\ITMO_programming_tools_lab4\CPPProject\libsegment_tree.dll D:\a\ITMO_programming_tools_lab4\ITMO_programming_tools_lab4\CPPProjectsegment_tree.cpp
+        run: g++ -shared -o CPPProject/libsegment_tree.dll CPPProject/segment_tree.cpp
+
+      - name: Check if DLL file exists (Windows)
+        if: matrix.os == 'windows-latest'
+        run: |
+          if exist "CPPProject\libsegment_tree.dll" (
+            echo "DLL file exists!"
+          ) else (
+            echo "DLL file not found!"
+            exit 1
+          )
 
       # Шаг 4: Устанавливаем зависимости
       - name: Install Python dependencies
